skinparam defaultFontName Carlito
skinparam defaultFontSize 13
skinparam shadowing false
skinparam roundCorner 10
skinparam ArrowColor #1B4332
skinparam ArrowFontSize 11
skinparam componentStyle rectangle
skinparam rectangle {
  BorderColor #1B4332
  BackgroundColor #FFFFFF
}
skinparam component {
  BorderColor #1B4332
  BackgroundColor #EEF4F0
}
skinparam database {
  BorderColor #1B4332
  BackgroundColor #FBF5E3
}
skinparam node {
  BorderColor #1B4332
  BackgroundColor #FFFFFF
}
skinparam cloud {
  BorderColor #C9A227
  BackgroundColor #FFFDF5
}
skinparam package {
  BorderColor #2D6A4F
  BackgroundColor #FFFFFF
  FontColor #1B4332
}
skinparam actor {
  BorderColor #1B4332
  BackgroundColor #C9A227
}
skinparam sequence {
  ParticipantBorderColor #1B4332
  ParticipantBackgroundColor #EEF4F0
  LifeLineBorderColor #2D6A4F
  ActorBorderColor #1B4332
  ActorBackgroundColor #C9A227
  GroupBorderColor #C9A227
}
skinparam noteBackgroundColor #FBF5E3
skinparam noteBorderColor #C9A227
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true
skinparam sequence {
  BoxBorderColor #C9A227
  BoxBackgroundColor #FFFDF5
}
hide footbox
